const MEDIA_TYPE_NA = "n-a";

const MEDIA_TYPE_ORDER =[
    "anime",
    "manga",
    "books",
    "game",
    "tv-show",
    "movie",
    "visual-novel",
    MEDIA_TYPE_NA,
];

const MEDIA_TYPE_LABELS = {
    "anime":        "Anime",
    "manga":        "Manga",
    "books":        "Books",
    "game":         "Game",
    "tv-show":      "TV Show",
    "movie":        "Movie",
    "visual-novel": "Visual Novel",
    [MEDIA_TYPE_NA]: "N/A",
};

const MEDIA_TYPE_COLORS = {
    "anime":        "#e879f9",
    "manga":        "#fb923c",
    "books":        "#d97706",
    "game":         "#4ade80",
    "tv-show":      "#60a5fa",
    "movie":        "#f472b6",
    "visual-novel": "#a78bfa",
    [MEDIA_TYPE_NA]: "#94a3b8",
};

const MEDIA_TYPE_MAP = {
    "Neon Genesis Evangelion":                          ["anime"],
    "Cowboy Bebop":                                     ["anime"],
    "Tengen Toppa Gurren Lagann":                       ["anime"],
    "Samurai Champloo":                                 ["anime"],
    "Ping Pong The Animation":                          ["anime"],
    "Ghost in the Shell: Stand Alone Complex":          ["anime"],
    "Mawaru Penguindrum":                               ["anime"],
    "Psycho-Pass":                                      ["anime"],
    "Code Geass":                                       ["anime"],
    "Run With The Wind":                                ["anime"],
    "SSSS.Dynazenon":                                   ["anime"],
    "Odd Taxi":                                         ["anime"],
    "Violet Evergarden":                                ["anime"],
    "Megalo Box":                                       ["anime"],
    "Megalo Box + Nomad":                               ["anime"],
    "Trigun Stampede":                                  ["anime"],
    "Hibike! Euphonium":                                ["anime"],
    "Kekkai Sensen":                                    ["anime"],
    "Rurouni Kenshin: Trust and Betrayal":              ["anime"],
    "Shouwa Genroku Rakugo Shinjuu":                    ["anime"],
    "Nana (Anime)":                                     ["anime", "manga"],
    "Re:Zero":                                          ["anime"],
    "Re:Zero Anime":                                    ["anime"],
    "The Tatami Galaxy":                                ["anime"],
    "The Tatami Galaxy & Time Machine Blues":           ["anime"],
    "Ouran High School Host Club":                      ["anime"],
    "Kare Kano":                                        ["anime"],
    "A Silent Voice":["anime", "movie"],
    "86":                                               ["anime"],
    "Digimon":                                          ["anime"],
    "Digimon Adventure 02":                             ["anime"],
    "Digimon Tamers":["anime"],
    "Baccano!":                                         ["anime"],
    "Durarara!!":                                       ["anime"],
    "Beastars (Primarily the anime)":                   ["anime", "manga"],
    "Hunter x Hunter":["anime", "manga"],
    "Haikyuu":                                          ["anime", "manga"],
    "Haikyuu!!":                                        ["anime", "manga"],
    "Berserk":["anime", "manga"],
    "Attack on Titan":                                  ["anime", "manga"],
    "One Piece":                                        ["anime", "manga"],
    "Naruto":["anime", "manga"],
    "Bleach":                                           ["anime", "manga"],
    "Death Note":                                       ["anime"],
    "Fullmetal Alchemist: Brotherhood":["anime"],
    "Jujutsu Kaisen":                                   ["anime", "manga"],
    "Chainsaw Man":                                     ["anime", "manga"],
    "Vinland Saga":                                     ["anime", "manga"],
    "Beastars":                                         ["anime", "manga"],
    "Monogatari Series":                                ["anime"],
    "Gintama":                                          ["anime"],
    "Kaguya-Sama: Love is War":["anime"],
    "Kaguya-Sama: Love Is War":["anime"],
    "Tokyo Ghoul":                                      ["anime", "manga"],
    "My Hero Academia":                                 ["anime", "manga"],
    "Kuroko no Basket":["anime"],
    "Dungeon Meshi":                                    ["anime"],
    "Made in Abyss":                                    ["anime"],
    "Houseki no Kuni":                                  ["anime", "manga"],
    "Blue Lock":                                        ["anime", "manga"],
    "Sangatsu no Lion":                                 ["anime"],
    "Chihayafuru":                                      ["anime"],
    "Hyouka":["anime"],
    "Monster":                                          ["anime"],
    "Yu Yu Hakusho":                                    ["anime"],
    "Hajime no Ippo":["anime"],
    "The Apothecary Diaries":                           ["anime"],
    "JoJo's Bizarre Adventure Part 7: Steel Ball Run":  ["anime", "manga"],
    "Vinland Saga (Anime + Manga)":                     ["anime", "manga"],
    "Oyasumi PunPun":                                   ["manga"],
    "Vagabond":                                         ["manga"],
    "Blue Period":["anime","manga"],
    "Blue Period (Manga)":                              ["anime","manga"],
    "Kagurabachi":                                      ["manga"],
    "Akane-banashi":                                    ["anime","manga"],
    "Orb: On The Movements of the Earth":               ["anime"],
    "Kaoru Hana":                                       ["anime"],
    "The Summer Hikaru Died":                           ["anime"],
    "Ikoku Nikki":                                      ["anime"],
    "Final Fantasy VI":                                 ["game"],
    "Final Fantasy VII":                                ["game"],
    "Final Fantasy VII (Original)":                     ["game"],
    "Final Fantasy VII Remake":                         ["game"],
    "Final Fantasy VII Remake + Rebirth":               ["game"],
    "Final Fantasy VII Franchise":["game"],
    "Final Fantasy VIII":                               ["game"],
    "Final Fantasy IX":                                 ["game"],
    "Final Fantasy X":                                  ["game"],
    "Final Fantasy XII":                                ["game"],
    "Final Fantasy XIV":                                ["game"],
    "Final Fantasy XV":                                 ["game"],
    "Final Fantasy Tactics: War of the Lions":          ["game"],
    "Final Fantasy Tactics: The Ivalice Chronicles":    ["game"],
    "Chrono Trigger":                                   ["game"],
    "The Legend of Zelda: Twilight Princess":           ["game"],
    "The Legend of Zelda: The Wind Waker":              ["game"],
    "The Legend of Zelda: Link's Awakening":            ["game"],
    "The Legend of Zelda: Ocarina of Time":             ["game"],
    "The Legend of Zelda: Majora's Mask":               ["game"],
    "The Legend of Zelda - Ocarina of Time, Majora's Mask and Twilight Princess": ["game"],
    "Pokemon Platinum":                                 ["game"],
    "Pokemon Black and White":                          ["game"],
    "Animal Crossing":                                  ["game"],
    "Animal Crossing (Gamecube)":                       ["game"],
    "NieR:Automata":                                    ["game"],
    "NieR:Replicant":                                   ["game"],
    "Nier Automata":                                    ["game"],
    "Nier Replicant":                                   ["game"],
    "NieR:Replicant + NieR:Automata":                   ["game"],
    "Xenoblade Chronicles":                             ["game"],
    "Xenoblade Chronicles 3":                           ["game"],
    "Bloodborne":                                       ["game"],
    "Elden Ring":                                       ["game"],
    "Dark Souls":                                       ["game"],
    "Dark Souls III":                                   ["game"],
    "Sekiro: Shadows Die Twice":                        ["game"],
    "God of War":                                       ["game"],
    "God of War 2018 + Ragnarok + Valhalla":            ["game"],
    "Yakuza/Like A Dragon Series":                      ["game"],
    "Disco Elysium":                                    ["game"],
    "Undertale":                                        ["game"],
    "Deltarune":                                        ["game"],
    "Undertale & Deltarune (Chapters 1 and 2)":         ["game"],
    "P.T.":                                             ["game"],
    "Silent Hill 2":                                    ["game"],
    "Silent Hill 2 + Remake":                           ["game"],
    "Silent Hill f":                                    ["game"],
    "Paper Mario: The Thousand Year Door":              ["game"],
    "Paper Mario: The Thousand Year Door (+ Remake)":   ["game"],
    "Super Mario Sunshine":                             ["game"],
    "Super Mario Galaxy":                               ["game"],
    "Super Mario Galaxy 1 & 2":                         ["game"],
    "Super Paper Mario":                                ["game"],
    "Paper Mario":                                      ["game"],
    "Mother 3":                                         ["game"],
    "Omori":                                            ["game"],
    "What Remains of Edith Finch":                      ["game"],
    "Baldur's Gate 3":["game"],
    "Danganronpa V3":                                   ["game"],
    "Ghost Trick: Phantom Detective":                   ["game"],
    "Dragon Age Origins":                               ["game"],
    "Dragon Quest XI":                                  ["game"],
    "Metal Gear Solid 2: Sons of Liberty":              ["game"],
    "Metal Gear Solid 3: Snake Eater":                  ["game"],
    "Persona 3 FES":                                    ["game"],
    "Persona 3 FES + The Answer":                       ["game"],
    "Persona 4 Golden":                                 ["game"],
    "Persona 5 Royal":                                  ["game"],
    "Fire Emblem: Three Houses":                        ["game"],
    "Fire Emblem Awakening":                            ["game"],
    "The Elder Scrolls IV: Oblivion":                   ["game"],
    "The Elder Scrolls V: Skyrim":                      ["game"],
    "Red Dead Redemption 2":                            ["game"],
    "The Last of Us":                                   ["game", "tv-show"],
    "Bioshock":                                         ["game"],
    "Sonic Adventure 2 Battle":                         ["game"],
    "Metaphor: ReFantazio":["game"],
    "Phoenix Wright: Ace Attorney Original Trilogy":    ["game"],
    "The Great Ace Attorney Chronicles":                ["game"],
    "Clair Obscur: Expedition 33":                      ["game"],
    "Lies of P":                                        ["game"],
    "Judgment Series":                                  ["game"],
    "Resident Evil Series":                             ["game"],
    "Alan Wake Series":                                 ["game"],
    "Until Then":                                       ["game"],
    "Mouthwashing":                                     ["game"],
    "Unicorn Overlord":                                 ["game"],
    "Until Dawn":                                       ["game"],
    "The Legend of Heroes/Trails Series":               ["game"],
    "Star Wars: Knights of the Old Republic II - The Sith Lords": ["game"],
    "Cyberpunk Universe / Edgerunners":["game", "anime"],
    "Cyberpunk Universe":                               ["game", "anime"],
    "The Witcher Video Game Series":                    ["game"],
    "The Witcher":                                      ["game"],
    "13 Sentinels: Aegis Rim":                          ["game"],
    "The Legend of Zelda: Ocarina of Time + Majora’s Mask": ["game"],
    "Pokemon Ruby/Sapphire/Emerald/Omega Ruby/Alpha Sapphire": ["game"],
    "Breaking Bad":                                     ["tv-show"],
    "Better Call Saul":["tv-show"],
    "Mad Men":                                          ["tv-show"],
    "Black Sails":                                      ["tv-show"],
    "Mindhunter":                                       ["tv-show"],
    "True Detective":                                   ["tv-show"],
    "Succession":                                       ["tv-show"],
    "Supernatural":                                     ["tv-show"],
    "Supernatural Seasons 1-5":["tv-show"],
    "Six Feet Under":                                   ["tv-show"],
    "The Sopranos":                                     ["tv-show"],
    "The Wire":                                         ["tv-show"],
    "Community":                                        ["tv-show"],
    "Hannibal":                                         ["tv-show"],
    "Peaky Blinders":                                   ["tv-show"],
    "The Boys":                                         ["tv-show"],
    "The Penguin":                                      ["tv-show"],
    "A Knight of the Seven Kingdoms":                   ["tv-show"],
    "Arcane":                                           ["tv-show"],
    "Avatar: The Last Airbender":                       ["tv-show"],
    "Spongebob Squarepants":["tv-show"],
    "Squid Game":                                       ["tv-show"],
    "Mr. Robot":                                        ["tv-show"],
    "Breaking Bad + Better Call Saul":                  ["tv-show"],
    "Fight Club":                                       ["movie"],
    "The Dark Knight":                                  ["movie"],
    "The Batman":                                       ["movie"],
    "Parasite":                                         ["movie"],
    "Inception":                                        ["movie"],
    "The Departed":                                     ["movie"],
    "Shutter Island":                                   ["movie"],
    "Se7en":                                            ["movie"],
    "The Matrix":                                       ["movie"],
    "Whiplash":                                         ["movie"],
    "Memento":                                          ["movie"],
    "The Grand Budapest Hotel":["movie"],
    "Oppenheimer":                                      ["movie"],
    "The Wolf of Wall Street":                          ["movie"],
    "The Lord of the Rings Film Trilogy":               ["movie"],
    "The Lord of the Rings: The Fellowship of the Ring": ["movie"],
    "The Lord of the Rings: The Two Towers":            ["movie"],
    "Sam Raimi Spiderman Trilogy":                      ["movie"],
    "Pirates of the Caribbean":                         ["movie"],
    "Pirates of the Caribbean Original Trilogy":        ["movie"],
    "Puss in Boots: The Last Wish":                     ["movie"],
    "Star Wars Episodes I-III":                         ["movie"],
    "Marty Supreme":                                    ["movie"],
    "Nosferatu (2024)":                                 ["movie"],
    "Harry Potter":                                     ["movie"],
    "The Spiderverse Series":                           ["movie"],
    "Into The Spiderverse":                             ["movie"],
    "Across The Spiderverse":                           ["movie"],
    "Harry Potter and the Prisoner of Azkaban (Film)":  ["movie"],
    "Umineko no Naku Koro Ni":                          ["game","visual-novel","manga"],
    "Umineko no Naku Koro ni":                          ["game","visual-novel","manga"],
    "The House in Fata Morgana":                        ["game","visual-novel"],
    "The House in Fata Morgana + A Requiem for Innocence": ["game","visual-novel"],
    "The House in Fata Morgana: A Requiem for Innocence": ["game","visual-novel"],
    "Steins;Gate":["game","visual-novel", "anime"],
    "Fate/Zero":                                        ["anime"],
    "Fate/Stay Night":                                  ["game","visual-novel", "anime"],
    "Fate/Hollow Ataraxia":["game","visual-novel"],
    "Fate Series":                                      ["game","visual-novel", "anime"],
    "A Song of Ice and Fire":                           ["books"],
    "A Song of Ice and Fire (Books)":                   ["books"],
    "Cyberpunk Universe (2077 + Phantom Liberty + Edgerunners)": ["game", "anime"],
    "Psycho-Pass (Season 1)":                           ["anime"],
    "Neon Genesis Evangelion + End of Evangelion":      ["anime"],
    "Digimon (S1-S3)":                                  ["anime"],
    "Digimon Adventures 02":                            ["anime"],
    "Gurren Lagann":                                    ["anime"],
    "The Legend of Korra":["tv-show"],
    "Megalo Box Nomad":                                 ["anime"],
    "Ghost in the Shell: Stand Alone Complex 2nd Gig":  ["anime"],
    "SSSS.Gridman":                                     ["anime"],
    "Hibike Euphonium":                                 ["anime"],
    "Hunter x Hunter - Ongoing":                        ["anime", "manga"],
    "Akane-banashi - Ongoing":["anime","manga"],
    "Kagurabachi - Ongoing 86 Chapters":                ["manga"],
    "Ongoing - One Piece":                              ["anime", "manga"],
    "Yu-Gi-Oh!":                                        ["anime"],
    "JoJo’s Bizarre Adventure Part 7: Steel Ball Run":  ["manga"],
    "Fullmetal Alchemist":                              ["anime"],
    "Monogatari":                                       ["anime"],
    "Tokyo Ghoul Part 1":                               ["manga", "anime"],
    "Dragon Ball":                                      ["anime", "manga"],
    "The Legend of Heroes/Trails Series (Up until Trails into Reverie)": ["game"],
    "Silent Hill 2 (Original and Remake)":              ["game"],
    "Silent Hill 2 + Remake":                           ["game"],
    "The Legend of Zelda: Breath of the Wild":          ["game"],
    "God of War Ragnarok: Valhalla":                    ["game"],
    "Judgment Series (Judgment + Lost Judgment)":       ["game"],
    "Ghost Trick: Phantom Detective":                   ["game"],
    "Ghost Trick":                                      ["game"],
    "The Legend of Zelda - Ocarina of Time, Majora’s Mask and Twilight Princess": ["game"],
    "Yakuza 5":                                         ["game"],
    "Metal Gear Solid series":                          ["game"],
    "Metal Gear Solid Series":                          ["game"],
    "Metal Gear Solid":                                 ["game"],
    "Metal Gear Solid 2":                               ["game"],
    "The Ace Attorney Original Trilogy":                ["game"],
    "Trails Series":                                    ["game"],
    "Final Fantasy IV":                                 ["game"],
    "Cyberpunk 2077":                                   ["game"],
    "Cyberpunk 2077: Phantom Liberty":                  ["game"],
    "The Witcher 3: Hearts of Stone":                   ["game"],
    "The Witcher 3: Blood and Wine":                    ["game"],
    "The Witcher 3: Wild Hunt":                         ["game"],
    "The Witcher 3: Wild Hunt - Blood & Wine":          ["game"],
    "The Legend of Zelda series":                       ["game"],
    "Final Fantasy 7 Franchise":                        ["game"],
    "Pokemon Black & White":                            ["game"],
    "Super Paper Mario":                                ["game"],
    "Apollo Justice: Ace Attorney":                     ["game"],
    "Lost Judgment":                                    ["game"],
    "Persona 4":                                        ["game"],
    "Sekiro":                                           ["game"],
    "Yakuza Kiwami 2":                                  ["game"],
    "Yakuza 0":                                         ["game"],
    "Yakuza 3":                                         ["game"],
    "Yakuza 6: A Song of Life":["game"],
    "Bioshock Infinite":                                ["game"],
    "Final Fantasy XIV: Shadowbringers":                ["game"],
    "Resident Evil 2":                                  ["game"],
    "Alan Wake II":                                     ["game"],
    "Death Stranding":                                  ["game"],
    "Pokemon Heart Gold/Soul Silver":                   ["game"],
    "Undertale + Deltarune":                            ["game"],
    "Like A Dragon: Infinite Wealth":                   ["game"],
    "Supernatural (Seasons 1-5)":                       ["tv-show"],
    "Spongebob Squarepants (Seasons 1-3)":              ["tv-show"],
    "True Detective (Season 1)":["tv-show"],
    "Breaking Bad & Better Call Saul":                  ["tv-show"],
    "Friday Night Lights":                              ["tv-show", "movie"],
    "Andor + Rogue One":                                ["tv-show"],
    "The Pitt":                                         ["tv-show"],
    "The Social Network":                               ["movie"],
    "The Pirates of the Caribbean (Original Trilogy)":  ["movie"],
    "Star Wars Episode III: Revenge of the Sith":       ["movie"],
    "The Lord of the Rings films":                      ["movie"],
    "Spiderverse series":                               ["movie"],
    "The Avengers":                                     ["movie"],
    "The Lion King":                                    ["movie"],
    "American Psycho":                                  ["movie"],
    "Nolan Batman Trilogy AND The Batman":              ["movie"],
    "Fate/Stay Night + Fate/Hollow Ataraxia":           ["game","visual-novel", "anime"],
    "Fate/Stay Night Visual Novel":                     ["game","visual-novel", "anime"],
    "A Song of Ice and Fire + Game of Thrones":["books"],
    "Bleach: Can’t Fear Your Own World":["books", "manga"],
    "Jujutsu Kaisen Modulo":                            ["anime","manga"],
    "Fire Punch":                                       ["manga"],
    "Culling Games (Jujutsu Kaisen 137-221)":           ["anime","manga"],
    "Silent Hill 2, Original and Remake":               ["game"],
    "Nana":["anime", "manga"],
    "Orb: On The Movements Of The Earth":               ["anime"],
    "Orb: On The Movements of the Earth Protagonists":  ["anime"],
    "Yu-Gi-Oh":                                         ["anime"],
    "The Legend of Zelda: Majora’s Mask":["game"],
    "The Legend of Zelda: Link’s Awakening":            ["game"],
    "Attack On Titan":                                  ["anime", "manga"],
    "Judgment":                                         ["game"],
    "Akane-Banashi":                                    ["anime","manga"],
    "MGS":                                              ["game"],
    "Baldur’s Gate 3":                                  ["game"],
    "Gwyn":                                             ["game"],
    "Morgott":                                          ["game"],
    "Run With the Wind":                                ["anime", "manga"],
    "Bleach*":                                          ["anime", "manga"],
    "The Dark Knight Rises":                            ["movie"],
    "Harry Potter Book Series":                         ["books"],
    "Kyousougiga":                                      ["anime"],
    "Kare Kano (Anime)":                                ["anime"],
    "Sangatsu no Lion (Anime)":                         ["anime"],
    "Shutter Island (Film)":                            ["movie"],
    "Re:Zero (Anime)":                                  ["anime"],
    "Friday Night Lights (TV Show)":                    ["tv-show"],
    "Yakuza Series":                                    ["game"],
    "Yakuza":                                           ["game"],
    "Cyberpunk: Edgerunners":                           ["anime"],
    "Into the Spiderverse":                             ["movie"],
    "True Detective Season 1":                          ["tv-show"],
    "NieR: Automata":                                   ["game"],
    "The Hobbit":                                       ["movie", "books"],
    "Books primarily":                                  ["books"],
    "Sam Raimi Trilogy":                                ["movie"],
    "MCU":                                              ["movie"],
    "Final Fantasy XVI":                                ["game"],
    "Renji Abarai (Bleach)*":                           ["anime","manga"],
};

function getEntrySeriesKey(entry) {
    if (entry.series) return entry.series;
    if (entry.name in MEDIA_TYPE_MAP) return entry.name;
    const m = entry.name.match(/\(([^()]+)\)\s*$/);
    return m ? m[1].trim() : entry.name;
}

function getMediaTypesForKey(key) {
    const types = MEDIA_TYPE_MAP[key];
    if (types && types.length) return types;
    return [MEDIA_TYPE_NA];
}
